// Generated by scripts/sync-locale-content.mjs.
// Edit the matching data/locales source dictionary, not this module.

export const CONTENT_METADATA = Object.freeze({
  "schemaVersion": 1,
  "language": "ko",
  "scope": "release",
  "sourceFingerprint": "f0dfa3a6ceb251406b8840c5734d22135353c0fccfaff1ae02ce804234e2522b"
});
export const CONTENT_TRANSLATIONS = Object.freeze({
  "Mobile bracket drags now stay inside the Tournament canvas without scrolling the page.": "모바일 대진표 드래그가 이제 페이지를 스크롤하지 않고 토너먼트 캔버스 안에 유지됩니다.",
  "Simpler mobile Tournament canvas": "더 단순해진 모바일 토너먼트 캔버스"
});
export const CONTENT_ENTITIES = Object.freeze({});

export default Object.freeze({
  ...CONTENT_METADATA,
  translations: CONTENT_TRANSLATIONS,
  entities: CONTENT_ENTITIES
});
