// Generated by scripts/sync-locale-content.mjs.
// Edit the matching data/locales source dictionary, not this module.

export const CONTENT_METADATA = Object.freeze({
  "schemaVersion": 1,
  "language": "es",
  "scope": "release",
  "sourceFingerprint": "d38f58b5ab0fb04c8c03f24b8054be0140dfb45c3194419f2350823ace46dff2"
});
export const CONTENT_TRANSLATIONS = Object.freeze({
  "Completed final days now open with a champion banner, confetti, background fireworks, and a three-point title story with player cards and a philosophy-led playing-style summary; later empty days keep the full celebration through August 2, then from August 3 retain only the calm World Cup is over message while the final remains available in Recent matches.": "Los días de finales ya concluidas ahora se abren con un banner del campeón, confeti, fuegos artificiales de fondo y un relato del título en tres puntos con tarjetas de jugadores y un resumen del estilo de juego guiado por su filosofía; en los días posteriores sin partidos se mantiene la celebración completa hasta el 2 de agosto y, desde el 3 de agosto, solo permanece el mensaje sereno de que el Mundial ha terminado, mientras la final sigue disponible en Partidos recientes.",
  "Every completed 2026 match now requires exactly three recap bullets in English and Chinese, with curated Spanish and Korean equivalents; validators, generators, and locale smoke tests enforce the contract so shortened or untranslated stories cannot silently ship.": "Cada partido completado de 2026 ahora debe tener exactamente tres puntos de resumen en inglés y chino, con equivalentes editados en español y coreano; los validadores, generadores y las pruebas rápidas de idiomas aplican esta regla para que los relatos abreviados o sin traducir no puedan publicarse silenciosamente.",
  "The dedicated 2026 highlights page brings together Spain's title run, every official award winner and why they stood out, and fan-favorite stories led by Cabo Verde, while the champion banner now stays focused on the title story.": "La página dedicada a los momentos destacados de 2026 reúne el camino de España al título, todos los ganadores de premios oficiales y por qué destacaron, y las historias favoritas de los aficionados encabezadas por Cabo Verde, mientras que el banner del campeón ahora se centra en la historia del título.",
  "World champions, richer archives, and smarter Ball Boy": "Campeones del mundo, archivos más completos y un Ball Boy más inteligente"
});
export const CONTENT_ENTITIES = Object.freeze({});

export default Object.freeze({
  ...CONTENT_METADATA,
  translations: CONTENT_TRANSLATIONS,
  entities: CONTENT_ENTITIES
});
