// Generated by scripts/sync-locale-content.mjs.
// Edit the matching data/locales source dictionary, not this module.

export const CONTENT_METADATA = Object.freeze({
  "schemaVersion": 1,
  "language": "es",
  "scope": "release",
  "sourceFingerprint": "2d7b94a437128c5a8e3b8b46b9c6299bff4fa168cc376fb9db2e2ab7956f4cba"
});
export const CONTENT_TRANSLATIONS = Object.freeze({
  "Audit and smoke coverage now guards the refreshed player-card and key-information contracts.": "Las auditorías y pruebas smoke ahora protegen los contratos actualizados de fichas de jugadores e información clave.",
  "Historical Key information briefs now use confirmed lineups and current structured localization.": "Los resúmenes históricos de Información clave ahora usan alineaciones confirmadas y la localización estructurada actual.",
  "Historical player cards now carry more specific tournament-time style notes across the archive.": "Las fichas históricas ahora incorporan notas de estilo más específicas de cada torneo en todo el archivo.",
  "Sharper historical player cards and match briefs": "Fichas históricas y resúmenes de partido más claros"
});
export const CONTENT_ENTITIES = Object.freeze({});

export default Object.freeze({
  ...CONTENT_METADATA,
  translations: CONTENT_TRANSLATIONS,
  entities: CONTENT_ENTITIES
});
